cask "font-harmonyos-sans" do
  version "2025.04.08"
  sha256 "ba7ddf71fc4dee33a7170869564ad76d421a2ed5c58e5aac9a573c39945ef654"

  url "https://developer.huawei.com/images/download/next/HarmonyOS-Sans.zip"
  name "HarmonyOS Sans"
  desc "HarmonyOS Sans font families"
  homepage "https://developer.huawei.com/consumer/cn/design/resource/"

  livecheck do
    skip "No version information available"
  end

  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_Heavy.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_SemiBold.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_Thin.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic UI/HarmonyOS_Sans_Naskh_ArabicUI_UltraLight.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_Heavy.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_SemiBold.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_Thin.ttf"
  font "HarmonyOS Sans/HarmonyOS Naskh Arabic/HarmonyOS_Sans_Naskh_Arabic_UltraLight.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans/HarmonyOS_Sans_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans/HarmonyOS_Sans_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans/HarmonyOS_Sans_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans/HarmonyOS_Sans_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans/HarmonyOS_Sans_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans/HarmonyOS_Sans_Semibold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans/HarmonyOS_Sans_Thin.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_SemiBold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed/HarmonyOS_Sans_Condensed_Thin.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed_Italic/HarmonyOS_SansCondensedItalic_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed_Italic/HarmonyOS_SansCondensedItalic_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed_Italic/HarmonyOS_SansCondensedItalic_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed_Italic/HarmonyOS_SansCondensedItalic_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed_Italic/HarmonyOS_SansCondensedItalic_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed_Italic/HarmonyOS_SansCondensedItalic_Semibold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Condensed_Italic/HarmonyOS_SansCondensedItalic_Thin.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Italic/HarmonyOS_SansItalic_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Italic/HarmonyOS_SansItalic_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Italic/HarmonyOS_SansItalic_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Italic/HarmonyOS_SansItalic_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Italic/HarmonyOS_SansItalic_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Italic/HarmonyOS_SansItalic_Semibold.ttf"
  font "HarmonyOS Sans/HarmonyOS_Sans_Italic/HarmonyOS_SansItalic_Thin.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansSC/HarmonyOS_SansSC_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansSC/HarmonyOS_SansSC_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansSC/HarmonyOS_SansSC_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansSC/HarmonyOS_SansSC_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansSC/HarmonyOS_SansSC_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansSC/HarmonyOS_SansSC_Semibold.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansSC/HarmonyOS_SansSC_Thin.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansTC/HarmonyOS_SansTC_Black.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansTC/HarmonyOS_SansTC_Bold.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansTC/HarmonyOS_SansTC_Light.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansTC/HarmonyOS_SansTC_Medium.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansTC/HarmonyOS_SansTC_Regular.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansTC/HarmonyOS_SansTC_Semibold.ttf"
  font "HarmonyOS Sans/HarmonyOS_SansTC/HarmonyOS_SansTC_Thin.ttf"
end
